import {
  create,
  NButton,
  NCard,
  NCheckbox,
  NDivider,
  NCollapse,
  NCollapseItem,
  NForm,
  NFormItem,
  NGradientText,
  NGrid,
  NGridItem,
  NInput,
  NDatePicker,
  NTimePicker,
  NAlert,
  NCarousel,
  NCarouselItem,
  NDrawer,
  NDrawerContent,
  NLayout,
  NLayoutHeader,
  NLayoutFooter,
  NLayoutContent,
  NSelect,
  NSpace,
  NTag,
  NText,
  NResult,
} from 'naive-ui';

export default {
  install(app) {
    const naive = create({
      components: [
        NButton,
        NCard,
        NCheckbox,
        NDivider,
        NCollapse,
        NCollapseItem,
        NForm,
        NFormItem,
        NGradientText,
        NGrid,
        NGridItem,
        NInput,
        NDatePicker,
        NTimePicker,
        NAlert,
        NCarousel,
        NCarouselItem,
        NDrawer,
        NDrawerContent,
        NLayout,
        NLayoutHeader,
        NLayoutFooter,
        NLayoutContent,
        NSelect,
        NSpace,
        NTag,
        NText,
        NResult,
      ],
    });
    app.use(naive);
  },
};
